//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementTable
    {
        public int SID { get; set; }
        public int ThisAccount { get; set; }
        public System.DateTime TDate { get; set; }
        public string FromAccount { get; set; }
        public string ToAccount { get; set; }
        public string Type { get; set; }
        public int OldBalance { get; set; }
        public int Amount { get; set; }
        public int NewBalance { get; set; }
    
        public virtual AccountsTable AccountsTable { get; set; }
    }
}
